services:
  stashly_tiuac_api:
    image: ${IMAGE_NAME:-app}:${IMAGE_TAG:-latest}
    container_name: stashly_tiuac_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8807:8807"
    volumes:
      - ./storage:/app/storage
    networks:
      - president

networks:
  president:
    external: true
